#数据库配置
spring:
  datasource:
    username: root
    password: 544869
    url: jdbc:mysql://localhost:3306/wb?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    password: 123456
  application:
    name: wb
mybatis:
  type-aliases-package: com.wb.entity
  mapper-locations: classpath:mybatis/mapper/*.xml
